# Generated by Django 2.2.3 on 2019-07-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_labor_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='part',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='part',
            name='unity',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor unitário'),
        ),
    ]
