# Generated by Django 2.2.3 on 2019-07-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190715_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odometer',
            field=models.IntegerField(blank=True, null=True, verbose_name='quilometragem'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.IntegerField(blank=True, null=True, verbose_name='quilometragem'),
        ),
    ]
